package mypals.ml.config;

import com.terraformersmc.modmenu.api.ConfigScreenFactory;
import com.terraformersmc.modmenu.api.ModMenuApi;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import mypals.ml.Lucidity;
import mypals.ml.features.selectiveRendering.WandActionsManager;
import net.minecraft.text.Text;
import net.minecraft.util.Formatting;

import java.awt.*;
import java.util.ArrayList;

import static mypals.ml.features.selectiveRendering.SelectiveRenderingManager.*;
import static mypals.ml.features.selectiveRendering.WandActionsManager.resolveWandMode;

public class LucidityModMenuIntegration implements ModMenuApi {
    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        var instance = LucidityConfig.CONFIG_HANDLER;
        return screen -> YetAnotherConfigLib.createBuilder()
                .title(Text.translatable("config.lucidity.title"))
                .category(
                        ConfigCategory.createBuilder()
                        .name(Text.translatable("config.lucidity.category.selectiveRenderings"))
                        //==================================================
                        .group(ListOption.<String>createBuilder()
                                .name(Text.translatable("config.lucidity.category.selectedBlock"))
                                .description
                                        (OptionDescription.createBuilder()
                                                .text(Text.translatable("config.lucidity.description.selectiveRenderings"))
                                                //.image(Lucidity.id("textures/main-render.png"), 192, 108)
                                                .build()
                                        )
                                .binding(
                                        new ArrayList<>(),
                                        () -> {
                                            // 返回配置值，确保非空
                                            if (instance.instance().selectedBlockTypes == null) {
                                                LucidityConfig.selectedBlockTypes = new ArrayList<>();
                                            }
                                            return instance.instance().selectedBlockTypes;
                                        },
                                        list -> instance.instance().selectedBlockTypes = list
                                )
                                .controller(StringControllerBuilder::create)
                                .initial("")
                                .build()
                        ).group(ListOption.<String>createBuilder()
                                        .name(Text.translatable("config.lucidity.category.selectedEntity"))
                                        .description
                                                (OptionDescription.createBuilder()
                                                        .text(Text.translatable("config.lucidity.description.selectiveRenderings"))
                                                        //.image(Lucidity.id("textures/main-render.png"), 192, 108)
                                                        .build()
                                                )
                                        .binding(
                                                new ArrayList<>(),
                                                () -> {
                                                    // 返回配置值，确保非空
                                                    if (instance.instance().selectedEntityTypes == null) {
                                                        LucidityConfig.selectedEntityTypes = new ArrayList<>();
                                                    }
                                                    return instance.instance().selectedEntityTypes;
                                                },
                                                list -> instance.instance().selectedEntityTypes = list
                                        )
                                        .controller(StringControllerBuilder::create)
                                        .initial("")
                                        .build()
                        ).group(ListOption.<String>createBuilder()
                                        .name(Text.translatable("config.lucidity.category.selectedParticle"))
                                        .description
                                                (OptionDescription.createBuilder()
                                                        .text(Text.translatable("config.lucidity.description.selectiveRenderings"))
                                                        //.image(Lucidity.id("textures/main-render.png"), 192, 108)
                                                        .build()
                                                )
                                        .binding(
                                                new ArrayList<>(),
                                                () -> {
                                                    if (instance.instance().selectedParticleTypes == null) {
                                                        LucidityConfig.selectedParticleTypes = new ArrayList<>();
                                                    }
                                                    return instance.instance().selectedParticleTypes;
                                                },
                                                list -> instance.instance().selectedParticleTypes = list
                                        )
                                        .controller(StringControllerBuilder::create)
                                        .initial("")
                                        .build()
                        ).group(ListOption.<String>createBuilder()
                                .name(Text.translatable("config.lucidity.option.selectedAreaRender"))
                                .description
                                (OptionDescription.createBuilder()
                                        .text(Text.translatable("config.lucidity.description.selectiveAreaRender"))
                                        .build()
                                )
                                .binding(
                                        new ArrayList<>(),
                                        () -> {
                                            // 返回配置值，确保非空
                                            if (instance.instance().selectedAreasSaved == null) {
                                                LucidityConfig.selectedAreasSaved = new ArrayList<>();
                                            }
                                            return instance.instance().selectedAreasSaved;
                                            },
                                        list -> instance.instance().selectedAreasSaved = list
                                )
                                .controller(StringControllerBuilder::create)
                                .initial("")
                                .build()
                        )
                        //==================================================
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("config.lucidity.category.selectiveRenderings"))
                                .description(
                                        OptionDescription.createBuilder()
                                                .text(Text.translatable("config.lucidity.description.selectiveRenderings"))
                                                .build()
                                ).option(
                                        Option.<Boolean>createBuilder()
                                                .name(Text.translatable("config.lucidity.option.spectator_select"))
                                                .description(OptionDescription.createBuilder()
                                                        .text(Text.translatable("config.lucidity.description.spectator_select"))
                                                        //.image(Lucidity.id(""), 192, 108)
                                                        .build()
                                                )
                                                .binding(true, () -> instance.instance().selectInSpectator, bool -> instance.instance().selectInSpectator = bool)
                                                .controller(BooleanControllerBuilder::create)
                                                .build()
                                )
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.wand"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.description.wand")))
                                        .binding("minecraft:breeze_rod", () -> instance.instance().wand, s -> instance.instance().wand = s)
                                        .controller(opt -> StringControllerBuilder.create(opt))
                                        .build()
                                ).option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.wand_apply"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.description.wand_apply")))
                                        .binding(0, () -> instance.instance().wandApplyMode, v -> instance.instance().wandApplyMode = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, WandActionsManager.WandApplyToMode.values().length-1)
                                                .step(1)
                                                .formatValue(val -> Text.translatable(resolveWandMode(val))))
                                        .build()
                                ).option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.render_mode.rendering_mode_block"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.render_mode.rendering_mode_block")))
                                        .binding(0, () -> instance.instance().renderModeBlock, v -> instance.instance().renderModeBlock = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, RenderMode.values().length-1)
                                                .step(1)
                                                .formatValue(val -> Text.translatable(resolveSelectiveBlockRenderingMode(val))))
                                        .build()
                                )
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.render_mode.rendering_mode_entity"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.render_mode.rendering_mode_entity")))
                                        .binding(0, () -> instance.instance().renderModeEntity, v -> instance.instance().renderModeEntity = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, RenderMode.values().length-1)
                                                .step(1)
                                                .formatValue(val -> Text.translatable(resolveSelectiveEntityRenderingMode(val))))
                                        .build()
                                )
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.render_mode.rendering_mode_particle"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.render_mode.rendering_mode_particle")))
                                        .binding(0, () -> instance.instance().renderModeParticle, v -> instance.instance().renderModeParticle = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, RenderMode.values().length-1)
                                                .step(1)
                                                .formatValue(val -> Text.translatable(resolveSelectiveParticleRenderingMode(val))))
                                        .build()
                                )
                                .build()
                        )

                        .build()
                ).category(
                        ConfigCategory.createBuilder()
                                .name(Text.translatable("config.lucidity.category.oreHighlight"))
                                //==================================================
                                .group(OptionGroup.createBuilder()
                                        .name(Text.translatable("config.lucidity.category.oreHighlight"))
                                        .description(
                                                OptionDescription.createBuilder()
                                                        .text(Text.translatable("config.lucidity.description.oreHighlight"))
                                                        .build()
                                        ).option(
                                                Option.<Boolean>createBuilder()
                                                        .name(Text.translatable("config.lucidity.option.oreHighlight"))
                                                        .description(OptionDescription.createBuilder()
                                                                .text(Text.translatable("config.lucidity.description.oreHighlight"))
                                                                .text(Text.of(""))
                                                                .text(Text.translatable("warn.lucidity.photosensitive-seizure-warning"))
                                                                .build()
                                                        )
                                                        .binding(false, () -> instance.instance().enableWorldEaterHelper, bool -> instance.instance().enableWorldEaterHelper = bool)
                                                        .controller(BooleanControllerBuilder::create)
                                                        .build()
                                        ).option(Option.<Integer>createBuilder()
                                                .name(Text.translatable("config.lucidity.option.oreHighlightRange"))
                                                .binding(20, () -> instance.instance().hightLightRange, v -> instance.instance().hightLightRange = v)
                                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                        .range(0, 100)
                                                        .step(1)
                                                        .formatValue(val -> Text.of(val.toString())))
                                                .build()
                                        )
                                        .build()
                                )

                                .build()
                ).category(
                        ConfigCategory.createBuilder()
                                .name(Text.translatable("config.lucidity.keyPresses"))
                                //==================================================
                                .group(OptionGroup.createBuilder()
                                        .name(Text.translatable("config.lucidity.keyPresses"))
                                        .description(
                                                OptionDescription.createBuilder()
                                                        .text(Text.translatable("config.lucidity.description.keyPresses"))
                                                        .build()
                                        ).option(
                                                Option.<Boolean>createBuilder()
                                                        .name(Text.translatable("config.lucidity.keyPresses"))
                                                        .description(OptionDescription.createBuilder()
                                                                .text(Text.translatable("config.lucidity.description.keyPresses"))
                                                                .build()
                                                        )
                                                        .binding(false, () -> instance.instance().renderKeyPresses, bool -> instance.instance().renderKeyPresses = bool)
                                                        .controller(BooleanControllerBuilder::create)
                                                        .build()
                                        )
                                        .build()
                                )

                                .build()
                ).category(
                        ConfigCategory.createBuilder()
                                .name(Text.translatable("config.lucidity.damageIndicator"))
                                //==================================================
                                .group(OptionGroup.createBuilder()
                                        .name(Text.translatable("config.lucidity.damageIndicator"))
                                        .description(
                                                OptionDescription.createBuilder()
                                                        .text(Text.translatable("config.lucidity.description.damageIndicator"))
                                                        .build()
                                        ).option(
                                                Option.<Boolean>createBuilder()
                                                        .name(Text.translatable("config.lucidity.damageIndicator.enable"))
                                                        .description(OptionDescription.createBuilder()
                                                                .text(Text.translatable("config.lucidity.description.damageIndicator"))
                                                                .build()
                                                        )
                                                        .binding(false, () -> instance.instance().enableDamageIndicator, bool -> instance.instance().enableDamageIndicator = bool)
                                                        .controller(BooleanControllerBuilder::create)
                                                        .build()
                                        ).option(
                                                Option.<Integer>createBuilder()
                                                        .name(Text.translatable("config.lucidity.damageIndicator.offset"))
                                                        .description(OptionDescription.createBuilder()
                                                                .text(Text.translatable("config.lucidity.description.damageIndicator.offset"))
                                                                .build()
                                                        )
                                                        .binding(0, () -> instance.instance().indicatorOffset, integer -> instance.instance().indicatorOffset = integer)
                                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                                .range(0, 50)
                                                                .step(1)
                                                                .formatValue(val -> Text.of(val.toString())))
                                                        .build()
                                        ).option(
                                                Option.<Integer>createBuilder()
                                                        .name(Text.translatable("config.lucidity.damageIndicator.time"))

                                                        .binding(0, () -> instance.instance().damageIndicatorLifeTime, integer -> instance.instance().damageIndicatorLifeTime = integer)
                                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                                .range(50, 100)
                                                                .step(1)
                                                                .formatValue(val -> Text.of(val.toString())))
                                                        .build()
                                        ).option(
                                                Option.<Color>createBuilder()
                                                        .name(Text.translatable("config.lucidity.damageIndicator.color"))

                                                        .binding(Color.red, () -> instance.instance().indicatorColor, color -> instance.instance().indicatorColor = color)
                                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                                .allowAlpha(true))
                                                        .build()
                                        )

                                        .build()
                                )

                                .build()
                ).category(ConfigCategory.createBuilder()
                        .name(Text.translatable("config.lucidity.category.explosion_visualizer"))

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("config.lucidity.group.renders"))
                                //.description(OptionDescription.of(Text.literal("Main mod features")))
                                .description(OptionDescription.createBuilder()
                                        .text(Text.translatable("config.lucidity.description.main_features"))
                                        .image(Lucidity.id("textures/all-explosives.png"), 192, 108)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.main_render"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.lucidity.option.description.main_render").formatted(Formatting.YELLOW))
                                                .image(Lucidity.id("textures/main-render.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(true, () -> instance.instance().showInfo, bool -> instance.instance().showInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.block_destruction"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.lucidity.option.description.block_destruction"))
                                                .image(Lucidity.id("textures/block-destruction.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(false, () -> instance.instance().showBlockDestroyInfo, bool -> instance.instance().showBlockDestroyInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.block_detection_ray"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.lucidity.option.description.block_detection_ray"))
                                                .image(Lucidity.id("textures/ray.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(false, () -> instance.instance().showExplosionBlockDamageRayInfo, bool -> instance.instance().showExplosionBlockDamageRayInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.sample_points"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.lucidity.option.description.sample_points"))
                                                .image(Lucidity.id("textures/sample-points.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(false, () -> instance.instance().showRayCastInfo, bool -> instance.instance().showRayCastInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.explosion_damage"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.lucidity.option.description.explosion_damage"))
                                                .image(Lucidity.id("textures/damage.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(false, () -> instance.instance().showDamageInfo, bool -> instance.instance().showDamageInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("config.lucidity.group.block_detection_ray_settings"))
                                .description(OptionDescription.createBuilder()
                                        .text(Text.translatable("config.lucidity.description.block_detection_ray_settings"))
                                        .image(Lucidity.id("textures/example.png"), 500, 500)
                                        .build()
                                )
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.x_min"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.x_min")))
                                        .binding(0, () -> instance.instance().Xmin, v -> instance.instance().Xmin = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.x_max"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.x_max")))
                                        .binding(16, () -> instance.instance().Xmax, v -> instance.instance().Xmax = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.y_min"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.y_min")))
                                        .binding(0, () -> instance.instance().Ymin, v -> instance.instance().Ymin = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.y_max"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.y_max")))
                                        .binding(16, () -> instance.instance().Ymax, v -> instance.instance().Ymax = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.z_min"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.z_min")))
                                        .binding(0, () -> instance.instance().Zmin, v -> instance.instance().Zmin = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.z_max"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.z_max")))
                                        .binding(16, () -> instance.instance().Zmax, v -> instance.instance().Zmax = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.invert"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.lucidity.option.description.invert"))
                                                .image(Lucidity.id("textures/invert.png"), 192, 108)
                                                .build())
                                        .binding(false, () -> instance.instance().Invert, bool -> instance.instance().Invert = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.layer_min"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.layer_min")))
                                        .binding(0, () -> instance.instance().LayerMin, v -> instance.instance().LayerMin = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 100)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.layer_max"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.layer_max")))
                                        .binding(100, () -> instance.instance().LayerMax, v -> instance.instance().LayerMax = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 100)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.block_detection_ray_icon"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.block_detection_ray_icon")))
                                        .binding("⧈", () -> instance.instance().BlockDetectionRayIcon, v -> instance.instance().BlockDetectionRayIcon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )

                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.block_detection_ray_icon_size"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.block_detection_ray_icon_size")))
                                        .binding(0.005F, () -> instance.instance().BlockDetectionRayIconSize, v -> instance.instance().BlockDetectionRayIconSize = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .range(0F, 0.1F)
                                                .step(0.005F)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.render_with_alpha"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.render_with_alpha")))
                                        .binding(false, () -> instance.instance().EnableAlpha, bool -> instance.instance().EnableAlpha = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build()
                                )
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.see_Throw"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.see_Throw")))
                                        .binding(false, () -> instance.instance().BlockDetectionRaySeeThrow, bool -> instance.instance().BlockDetectionRaySeeThrow = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build()
                                )

                                .build()
                        )

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("config.lucidity.option.block_destruction_render_settings"))
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.block_destruction_render_color"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.block_destruction_render_color")))
                                        .binding(Color.YELLOW, () -> instance.instance().BlockDestroyIconColor, v -> instance.instance().BlockDestroyIconColor = v)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build()
                                )
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.block_destruction_render_icon"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.block_destruction_render_icon")))
                                        .binding("!", () -> instance.instance().BlockDestroyIcon, v -> instance.instance().BlockDestroyIcon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.block_destruction_render_icon_size"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.block_destruction_render_icon_size")))
                                        .binding(0.05F, () -> instance.instance().BlockDestroyIconSize, v -> instance.instance().BlockDestroyIconSize = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .range(0F, 0.2F)
                                                .step(0.05F)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.see_Throw"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.see_Throw")))
                                        .binding(true, () -> instance.instance().BlockDestroyIconSeeThrow, bool -> instance.instance().BlockDestroyIconSeeThrow = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build()
                                )
                                .build()
                        )

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("config.lucidity.option.entity_sample_point_render_settings"))
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.entity_sample_point_safe_color"))
                                        .binding(Color.GREEN, () -> instance.instance().EntitySamplePoion_Safe_IconColor, v -> instance.instance().EntitySamplePoion_Safe_IconColor = v)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build()
                                )
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.entity_sample_point_safe_icon"))
                                        .binding("√", () -> instance.instance().EntitySamplePoion_Safe_Icon, v -> instance.instance().EntitySamplePoion_Safe_Icon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.entity_sample_point_danger_color"))
                                        .binding(Color.RED, () -> instance.instance().EntitySamplePoion_Danger_IconColor, v -> instance.instance().EntitySamplePoion_Danger_IconColor = v)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build()
                                )
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.entity_sample_point_danger_icon"))
                                        .binding("X", () -> instance.instance().EntitySamplePoion_Danger_Icon, v -> instance.instance().EntitySamplePoion_Danger_Icon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.entity_sample_point_blocked_color"))
                                        .binding(Color.MAGENTA, () -> instance.instance().EntitySamplePoion_Blocked_IconColor, v -> instance.instance().EntitySamplePoion_Blocked_IconColor = v)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build()
                                )
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.entity_sample_point_blocked_icon"))
                                        .binding("❖", () -> instance.instance().EntitySamplePoion_Blocked_Icon, v -> instance.instance().EntitySamplePoion_Blocked_Icon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.entity_sample_point_icon_size"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.entity_sample_point_icon_size")))
                                        .binding(0.01F, () -> instance.instance().EntitySamplePoionIconSize, v -> instance.instance().EntitySamplePoionIconSize = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .range(0F, 0.03F)
                                                .step(0.01F)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.lucidity.option.see_Throw"))
                                        .description(OptionDescription.of(Text.translatable("config.lucidity.option.description.see_Throw")))
                                        .binding(true, () -> instance.instance().EntitySamplePointSeeThrow, bool -> instance.instance().EntitySamplePointSeeThrow = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build()
                                )

                                .build()
                        )
                        .build()
                )
                .save(() -> {
                    instance.save();
                    Lucidity.onConfigUpdated();
                })
                .build()
                .generateScreen(screen);
    }
}
